=== cyanolive/ApiTestExtension2/API-XML/template.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2011 (http://www.altova.com)-->
<!ELEMENT root ((api+))>
<!ATTLIST  root
	product CDATA #REQUIRED
>
<!ELEMENT scene (#PCDATA)>
<!ELEMENT api ((name, apiulr, function, scene?, menuFolder, menuText, request, response))>
<!ELEMENT request ((param*))>
<!ATTLIST request
	type (GET | POST | PUT | DELETE) #REQUIRED
>
<!ELEMENT response ((item*))>
<!ATTLIST response
	type (raw | json_dict | json_list) #REQUIRED
>
<!ELEMENT remark (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT function (#PCDATA)>
<!ELEMENT apiulr (#PCDATA)>
<!ELEMENT menuFolder (#PCDATA)>
<!ELEMENT menuText (#PCDATA)>
<!ELEMENT menuTextOrder (#PCDATA)>
<!ELEMENT item ((name, remark, (item*)))>
<!ATTLIST item
	type (int | dict | list | string | bool) #REQUIRED
>
<!ELEMENT param ((paraname, paraInstruction, paradefault?))>
<!ELEMENT paraname (#PCDATA)>
<!ELEMENT paraInstruction (#PCDATA)>
<!ELEMENT paradefault (#PCDATA)>
<!ATTLIST param
	type (int | string | bool) #REQUIRED
>
<!ATTLIST param
	compulsory (true | false) #REQUIRED
>

=== cyanolive/ApiTestExtension2/API-XML/lottery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by pgao (bainainfo) -->
<!DOCTYPE root SYSTEM "template.dtd">
<root product="Lottery">
	<api>
		<name>ok</name>
		<apiulr>/duobao/api/v1/sso_login/ok</apiulr>
		<function>OK登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>OK登录</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>thirdpartyId</paraname>
				<paraInstruction>第三方登录id</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>accessToken</paraname>
				<paraInstruction>第三方token</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="string">
				<name>reason</name>
				<remark>登录失败的原因</remark>
			</item>
			<item type="dict">
				<name>status</name>
				<remark>用户登录的状态1-成功，0-失败</remark>
			</item>
			<item type="dict">
				<name>account</name>
				<remark>返回的结果dict</remark>
				<item type="string">
					<name>token</name>
					<remark>返回的服务端token</remark>
				</item>
				<item type="dict">
					<name>user</name>
					<remark>宝贝获奖者的信息dict</remark>
					<item type="int">
						<name>uid</name>
						<remark>用户id（用户唯一标识）</remark>
					</item>
					<item type="string">
						<name>nickname</name>
						<remark>用户昵称</remark>
					</item>
					<item type="string">
						<name>mobile</name>
						<remark>用户电话号码</remark>
					</item>
					<item type="string">
						<name>imgUrl</name>
						<remark>用户头像url</remark>
					</item>
					<item type="int">
						<name>balance</name>
						<remark>用户账户的剩余coin</remark>
					</item>
				</item>
			</item>
		</response>
	</api>
	<api>
		<name>fb</name>
		<apiulr>/duobao/api/v1/sso_login/fb</apiulr>
		<function>facebook登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>facebook登录</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>thirdpartyId</paraname>
				<paraInstruction>第三方登录id</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>accessToken</paraname>
				<paraInstruction>第三方token</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="string">
				<name>reason</name>
				<remark>登录失败的原因</remark>
			</item>
			<item type="dict">
				<name>status</name>
				<remark>用户登录的状态1-成功，0-失败</remark>
			</item>
			<item type="dict">
				<name>account</name>
				<remark>返回的结果dict</remark>
				<item type="string">
					<name>token</name>
					<remark>返回的服务端token</remark>
				</item>
				<item type="dict">
					<name>user</name>
					<remark>宝贝获奖者的信息dict</remark>
					<item type="int">
						<name>uid</name>
						<remark>用户id（用户唯一标识）</remark>
					</item>
					<item type="string">
						<name>nickname</name>
						<remark>用户昵称</remark>
					</item>
					<item type="string">
						<name>mobile</name>
						<remark>用户电话号码</remark>
					</item>
					<item type="string">
						<name>imgUrl</name>
						<remark>用户头像url</remark>
					</item>
					<item type="int">
						<name>balance</name>
						<remark>用户账户的剩余coin</remark>
					</item>
				</item>
			</item>
		</response>
	</api>
	<api>
		<name>vk</name>
		<apiulr>/duobao/api/v1/sso_login/vk</apiulr>
		<function>vk登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>vk登录</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>thirdpartyId</paraname>
				<paraInstruction>第三方登录id</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>accessToken</paraname>
				<paraInstruction>第三方token</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="string">
				<name>reason</name>
				<remark>登录失败的原因</remark>
			</item>
			<item type="dict">
				<name>status</name>
				<remark>用户登录的状态1-成功，0-失败</remark>
			</item>
			<item type="dict">
				<name>account</name>
				<remark>返回的结果dict</remark>
				<item type="string">
					<name>token</name>
					<remark>返回的服务端token</remark>
				</item>
				<item type="dict">
					<name>user</name>
					<remark>宝贝获奖者的信息dict</remark>
					<item type="int">
						<name>uid</name>
						<remark>用户id（用户唯一标识）</remark>
					</item>
					<item type="string">
						<name>nickname</name>
						<remark>用户昵称</remark>
					</item>
					<item type="string">
						<name>mobile</name>
						<remark>用户电话号码</remark>
					</item>
					<item type="string">
						<name>imgUrl</name>
						<remark>用户头像url</remark>
					</item>
					<item type="int">
						<name>balance</name>
						<remark>用户账户的剩余coin</remark>
					</item>
				</item>
			</item>
		</response>
	</api>
	<api>
		<name>wx</name>
		<apiulr>/duobao/api/v1/sso_login/wx</apiulr>
		<function>微信登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>微信登录</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>thirdpartyId</paraname>
				<paraInstruction>第三方登录id</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>accessToken</paraname>
				<paraInstruction>第三方token</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="string">
				<name>reason</name>
				<remark>登录失败的原因</remark>
			</item>
			<item type="dict">
				<name>status</name>
				<remark>用户登录的状态1-成功，0-失败</remark>
			</item>
			<item type="dict">
				<name>account</name>
				<remark>返回的结果dict</remark>
				<item type="string">
					<name>token</name>
					<remark>返回的服务端token</remark>
				</item>
				<item type="dict">
					<name>user</name>
					<remark>宝贝获奖者的信息dict</remark>
					<item type="int">
						<name>uid</name>
						<remark>用户id（用户唯一标识）</remark>
					</item>
					<item type="string">
						<name>nickname</name>
						<remark>用户昵称</remark>
					</item>
					<item type="string">
						<name>mobile</name>
						<remark>用户电话号码</remark>
					</item>
					<item type="string">
						<name>imgUrl</name>
						<remark>用户头像url</remark>
					</item>
					<item type="int">
						<name>balance</name>
						<remark>用户账户的剩余coin</remark>
					</item>
				</item>
			</item>
		</response>
	</api>
	<api>
		<name>logout</name>
		<apiulr>/duobao/api/v1/user/logout</apiulr>
		<function>用户退出登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>用户退出登录</menuText>
		<request type="POST">
			<param type="int" compulsory="true">
				<paraname>uid</paraname>
				<paraInstruction>用户id</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>token</paraname>
				<paraInstruction>用户令牌</paraInstruction>
			</param>
		</request>
		<response type="json_dict"/>
	</api>
	<api>
		<name>register</name>
		<apiulr>/duobao/api/v1/user/register</apiulr>
		<function>用户注册</function>
		<menuFolder>账号</menuFolder>
		<menuText>用户注册</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>mobile</paraname>
				<paraInstruction>注册手机号</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>password</paraname>
				<paraInstruction>注册密码加密密文</paraInstruction>
			</param>
			<param type="int" compulsory="true">
				<paraname>timestamp</paraname>
				<paraInstruction>请求时间戳</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>sign</paraname>
				<paraInstruction>注册请求签名</paraInstruction>
			</param>
		</request>
		<response type="json_dict"/>
	</api>
	<api>
		<name>checkMobileExists</name>
		<apiulr>/duobao/api/v1/user/mobileExists</apiulr>
		<function>检测手机用户是否已存在</function>
		<menuFolder>账号</menuFolder>
		<menuText>手机用户检测</menuText>
		<request type="GET">
			<param type="string" compulsory="true">
				<paraname>mobile</paraname>
				<paraInstruction>注册手机号</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="int">
				<name>status</name>
				<remark>注册预备状态码， 0-用户不存在， 1-用户已存在</remark>
			</item>
		</response>
	</api>
	<api>
		<name>login</name>
		<apiulr>/duobao/api/v1/user/login</apiulr>
		<function>用户登录</function>
		<menuFolder>账号</menuFolder>
		<menuText>用户登录</menuText>
		<request type="POST">
			<param type="string" compulsory="true">
				<paraname>mobile</paraname>
				<paraInstruction>注册手机号</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>password</paraname>
				<paraInstruction>注册密码加密密文</paraInstruction>
			</param>
			<param type="int" compulsory="true">
				<paraname>timestamp</paraname>
				<paraInstruction>请求时间戳</paraInstruction>
			</param>
			<param type="string" compulsory="true">
				<paraname>sign</paraname>
				<paraInstruction>注册请求签名</paraInstruction>
			</param>
		</request>
		<response type="json_dict">
			<item type="string">
				<name>reason</name>
				<remark>登录失败的原因</remark>
			</item>
			<item type="int">
				<name>status</name>
				<remark>用户登录的状态1-成功，0-失败</remark>
			</item>
			<item type="dict">
				<name>account</name>
				<remark>用户账户信息</remark>
				<item type="string">
					<name>token</name>
					<remark>返回的服务端token</remark>
				</item>
				<item type="dict">
					<name>user</name>
					<remark>宝贝获奖者的信息dict</remark>
					<item type="int">
						<name>uid</name>
						<remark>用户id</remark>
					</item>
					<item type="string">
						<name>nickname</name>
						<remark>用户昵称</remark>
					</item>
					<item type="string">
						<name>mobile</name>
						<remark>用户电话号码</remark>
					</item>
					<item type="string">
						<name>imgUrl</name>
						<remark>用户头像url</remark>
					</item>
					<item type="int">
						<name>balance</name>
						<remark>用户账户的剩余coin</remark>
					</item>
				</item>
			</item>
		</response>
	</api>
	<api>
		<name>list</name>
		<apiulr>/duobao/api/v1/goods/list</apiulr>
		<function>获取分类宝贝列表</function>
		<scene>获取首页及各分类页面宝贝列表</scene>
		<menuFolder>商品相关</menuFolder>
		<menuText>首页商品列表</menuText>
		<request type="GET">
			<param type="int" compulsory="true">
				<paraname>categoryId</paraname>
				<paraInstruction>商品类别id</paraInstruction>
			</param>
			<param type="int" compulsory="true">
				<paraname>sortId</paraname>
